# Generated by Django 5.2 on 2025-05-04 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDeferment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(max_length=100)),
                ('is_work_exp', models.BooleanField()),
                ('work_describe', models.CharField(max_length=255)),
                ('is_deferment', models.BooleanField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('deferment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationdeferment')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationfiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.catalogemployment')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.newsimg')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.CharField()),
                ('answer', models.CharField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
