# Generated by Django 5.2 on 2025-05-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='iin',
            field=models.CharField(max_length=16),
        ),
    ]
