# Generated by Django 5.2 on 2025-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_person_address_alter_person_date_of_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
        migrations.AlterField(
            model_name='person',
            name='iin',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
