# Generated by Django 5.2 on 2025-05-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_person_options_alter_person_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_numder',
            field=models.BigIntegerField(default=877777777777),
            preserve_default=False,
        ),
    ]
