# Generated by Django 5.2 on 2025-05-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
